{
 "title": "Keenetic",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (mac) (ip_hotspot_signal or ip_hotspot_speed))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "system_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average system usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n  avg_over_time(system_memtotal[$__interval])\r\n  - avg_over_time(system_memfree[$__interval])\r\n  - avg_over_time(system_membuffers[$__interval])\r\n  - avg_over_time(system_memcache[$__interval])\r\n)",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "avg_over_time(system_cpuload[$__interval])\r\n",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(\r\n  avg_over_time(system_swaptotal[$__interval])\r\n  - avg_over_time(system_swapfree[$__interval])\r\n)",
     "legendFormat": "SWAP Usage"
    }
   ]
  },
  {
   "title": "Internet status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(internet_status_internet[2m]) ",
     "legendFormat": "Internet"
    },
    {
     "expr": "last_over_time(internet_status_dns_accessible[2m])",
     "legendFormat": "DNS"
    },
    {
     "expr": "last_over_time(internet_status_gateway_accessible[2m])",
     "legendFormat": "Gateway"
    }
   ]
  },
  {
   "title": "Keenetic Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"Hopper\"}"
    }
   ]
  },
  {
   "title": "Interfaces data transfered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(interface_stat_rxbytes[$__range])) * -1",
     "legendFormat": "RX {{name}} "
    },
    {
     "expr": "sum by (name) (increase(interface_stat_txbytes[$__range]))",
     "legendFormat": "TX {{name}} "
    }
   ]
  },
  {
   "title": "Interfaces rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(interface_stat_txspeed[$__range])) by (name) ",
     "legendFormat": "TX {{name}}"
    },
    {
     "expr": "avg(rate(interface_stat_rxspeed[$__range])) by (name) * -1",
     "legendFormat": "RX {{name}}"
    }
   ]
  },
  {
   "title": "Data usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n  rate(ip_hotspot_rxbytes[$__range])\r\n  +\r\n  rate(ip_hotspot_txbytes[$__range])\r\n) > 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wi-Fi Clients signal level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "ip_hotspot_signal\r\n", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Wi-Fi Clients TX Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by (name, mode) (\r\n  ip_hotspot_txrate{mode!=\"\"}\r\n)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg(system_memtotal - system_memfree) by (hostname)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpuload\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free media space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "media_free", "legendFormat": "{{label}}" }
   ]
  }
 ]
}